### ISSUE TITLE
intent.util.DelayedFutureTest failure

### ISSUE THREAD

**Issue by bishabosha** [factor10/intent#44] opened 2020-01-08 12:30 UTC
This failed in the Dotty community build (currently based on 989f23893dc1041f69217276176cb6579db35778) 
```
[info] [FAILED] intent.util.DelayedFutureTest >> A DelayedFuture >> should be cancellable (383 ms)
[info] 	Expected false but found true (/tmp/3/community-build/community-projects/intent/src/test/scala/intent/util/DelayedFutureTest.scala:47:32)
[info] [FAILED] intent.util.DelayedFutureTest >> A DelayedFuture >> should have a default result after being cancelled (382 ms)
[info] 	Expected 0 but found 42 (/tmp/3/community-build/community-projects/intent/src/test/scala/intent/util/DelayedFutureTest.scala:55:35)
```

**Comment by provegard** [comment] 2020-01-08 12:57
Thanks, we'll look into it.

**Comment by eliasson** [comment] 2020-01-10 16:27
I failed to reproduce the error in the community build, but I am not sure I set everything up correctly.

Here is what I did:

```
git clone git@github.com:dotty-staging/dotty.git
git checkout change-extmethods3
git submodule update --init --recursive
```

I edited `community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala` to comment out all tests but `intent` and then ran the tests multiple times.

```
sbt community-build/test
…
> [info] Passed: Total 201, Failed 0, Errors 0, Passed 201, Ignored 1
```

I assumed this would compile and use the correct version of the dotty compiler? @bishabosha does it look correct to you?

To rule out any intermittent error I plan to run the test continously until failure later tonight using

`while sbt community-build/test; do :; done`

**Comment by eliasson** [comment] 2020-01-14 22:41
I realized that I forgot to update this thread. I ran the test continuously for a few hours during the weekend and could not reproduce this issue.

I noticed that the Dotty PR #7917 reporting this issue has been merged now and that Intent built without errors as well. 

Maybe this was an intermittent timing issue?

**Comment by bishabosha** [comment] 2020-01-15 09:33
Yeah I'm not sure what happened, but the Drone instance we've been running the tests often has issues related to thread sleeping, so Im not sure which part of the entire stack is at fault

**Comment by eliasson** [comment] 2020-01-15 15:42
Ok, I’ll leave this open for while longer to see if we can reproduce it somehow.

Let us know if it occures in your drone build again.

**Closed** 2020-09-18 12:54 UTC
